# Generated by Django 3.1.2 on 2022-02-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LenguajeDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Lenguaje de Base de Datos',
                'verbose_name_plural': 'Lenguajes de Bases de Datos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Lenguajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(max_length=150)),
                ('framework', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Situacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion', models.CharField(max_length=50)),
            ],
        ),
    ]
