# Generated by Django 3.1.2 on 2022-02-15 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('puerto', models.CharField(max_length=150)),
                ('servidor', models.CharField(max_length=150)),
                ('servidor_replica', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=50)),
                ('sql', models.BooleanField(default=True)),
                ('lenguaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.lenguajedb')),
            ],
            options={
                'verbose_name': 'Base',
                'verbose_name_plural': 'Bases',
                'ordering': ['id'],
            },
        ),
    ]
